version: '2'
services:
  app:
    build: .
    volumes:
      - .:/app
      - ./data:/data

  nginx:
    image: nginx:stable-alpine
    depends_on:
      - app
    volumes:
      - ./data:/data
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8085:80"
